services:

  debian-unstable-devel:
    command: ./build.sh
    environment:
      - R_VERSION=devel
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: builder/Dockerfile.debian-unstable-devel
    image: rhub/debian-unstable-devel:latest
    volumes:
      - ./integration/tmp:/tmp/output

  ubuntu-2204:
    command: ./build.sh
    environment:
      - R_VERSION=devel
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: builder/Dockerfile.ubuntu-2204
    image: rhub/ubuntu-2204:latest
    volumes:
      - ./integration/tmp:/tmp/output

  ubuntu-2204-nold:
    command: ./build.sh
    environment:
      - R_VERSION=devel
      - R_TYPE=-nold
      - XCONFIGURE_OPTIONS=--disable-long-double
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: builder/Dockerfile.ubuntu-2204-nold
    image: rhub/ubuntu-2204-nold:latest
    volumes:
      - ./integration/tmp:/tmp/output

  fedora-gcc:
    command: ./build.sh
    environment:
      - R_VERSION=devel
      - R_TYPE=-gcc
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: builder/Dockerfile.fedora-gcc
    image: rhub/fedora-gcc:latest
    volumes:
      - ./integration/tmp:/tmp/output

  fedora-gcc-13:
    command: ./build.sh
    environment:
      - R_VERSION=devel
      - R_TYPE=-gcc-13
      - LOCAL_STORE=/tmp/output
    build:
      context: .
      dockerfile: builder/Dockerfile.fedora-gcc-13
    image: rhub/fedora-gcc-13:latest
    volumes:
      - ./integration/tmp:/tmp/output
