project:
  type: website
  render:
    - "index.qmd"
    - "containers.qmd"
    - "local.qmd"
    - "gha.qmd"
    - "internals.qmd"

website:
  title: "R-hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: containers.qmd
        text: Containers
      - href: local.qmd
        text: Run on your machine
      - href: gha.qmd
        text: Run on GitHub Actions
    right:
      - href: internals.qmd
        text: Internals
      - href: https://github.com/r-hub/containers
        text: At GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
