
name: Check any R package at an URL

on:
  workflow_dispatch:
    inputs:
      inpurl:
        description: 'URL to a source R package'
        required: true
        type: string
      inpcont:
        description: 'Check container'
        required: true
        type: choice
        options:
        - 'atlas'
        - 'gcc-13'
        - 'nold'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/r-hub/containers/${{ github.event.inputs.inpcont }}:latest

    steps:
    - name: Download package
      run: |
        mkdir /check
        curl -LO "${{ github.event.inputs.inpurl }}" --output-dir /check

    - name: Install dependencies and check package
      run: r-check

    - name: Upload check result as artifact
      uses: actions/upload-artifact@v3
      with:
        name: check-results
        path: /check
