
name: Containers

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 5 * * *'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.setup-matrix.outputs.containers }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up matrix of containers
      id: setup-matrix
      run: |
        (echo -n 'containers=['; ls containers | sed 's|/$||' |
        awk '{ printf("\"%s\",", $1) }' | sed 's/,$//'; echo -n ']') >> $GITHUB_OUTPUT

  containers:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.setup-matrix.outputs.containers) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        context: containers/${{ matrix.container }}
        load: true
        tags: |
          rhub/test:test

    - name: Test
      run: |
        docker run rhub/test:test R --version

    - name: Push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        context: containers/${{ matrix.container }}
        push: true
        tags: |
          rhub/${{ matrix.container }}:latest
          ghcr.io/r-hub/containers/${{ matrix.container }}:latest
