
name: R builds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.setup-matrix.outputs.platforms }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up matrix of R builds
      id: setup-matrix
      run: |
        platforms=$(python tests/get-platforms.py)
        echo "platforms=$platforms" >> $GITHUB_OUTPUT

  package-files:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.setup-matrix.outputs.platforms) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Build base image
        run: docker-compose build ${{ matrix.platform }}

      - name: Build R
        run: docker-compose up ${{ matrix.platform }}

      - name: Copy package
        run: |
          pkg=$(find integration -name "*.deb" -or -name "*.rpm")
          cp "$pkg" .
          ls -l "$pkg"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-rstudio-*.deb
            *-rstudio-*.rpm
          name: "Latest builds"
          tag_name: latest
